name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-check'
        filter_mode: nofilter
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        clippy_flags: --all --all-targets --features full-async
