name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: dtolnay/rust-toolchain@master
          with:
            components: clippy
        - uses: actions-rs/clippy-check@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all --all-targets
